### PR TITLE
Android Fastlane releases

### PR DESCRIPTION
**Pull request by BenjaminAmos**
## Description
This pull request adds the necessary configuration to build and deploy Destination Sol via Fastlane. It creates some initial lanes to allow automated deployment of the game to Google Play, as well as to create a release APK on its own.

With these changes, most store and release metadata is now stored in the repository, including screenshots, video links and changelogs.

### Fastlane Lanes
I haven't tested any of these fully apart from `buildRelease` and  `deployInternalAppSharing`.
#### Release (`fastlane buildRelease`)
- Generates a release APK and signs it with the release keystore.
#### Internal App Sharing (`fastlane deployInternalAppSharing`)
- Deploys the game to Google Play via Internal App Sharing. Only very limited selected testers (up to 100) can access this build via Google Play.
#### Internal (`fastlane deployInternal`)
- Deploys the game to the internal track on Google Play. Only very limited selected testers (up to 100) can access this build via Google Play.
#### Alpha (`fastlane deployAlpha`)
- Deploys the game to the closed-alpha track on Google Play. Only selected testers can access this build via Google Play.
#### Beta (`fastlane deployBeta`)
- Deploys the game to the open-beta track on Google Play. This means that it is published as an opt-in beta for users on Google Play.
#### Production (`fastlane deployProduction`)
- Deploys the game to the production track on Google Play. This means that it is published for everyone.

## Usage
- You will need to install both ruby, bundler and access to a play store developer account to test this.
- To install fastlane, run `bundle install` in the `android` directory.
- Create a service account in the play console using the instructions at https://docs.fastlane.tools/getting-started/android/setup/#collect-your-google-credentials and save the key json file as `playstore_secret.json` in the `android` directory
- Create a `fastlane/.env` file based on the following template:
```ini
DESTSOL_ANDROID_SIGNING_KEYSTORE=<KEYSTORE>
DESTSOL_ANDROID_SIGNING_STORE_PASS=<KEYSTORE_PASS>
DESTSOL_ANDROID_SIGNING_KEY_ALIAS=<KEYSTORE_KEY_ALIAS>
DESTSOL_ANDROID_SINGING_KEY_PASS=<KEYSTORE_KEY_PASS>
```

## Notes
- This superceeds #6.
- This contributes to MovingBlocks/DestinationSol#425.
- I added a changelog file for the `2.0.0` release here, slightly modified from the original to remove the desktop-specific bits, I don't think that `2.0.0` was ever released to any stores on Android, so the changelog might not be needed.

### CODE REVIEW

**Comment by NicholasBatesNZ** [comment]
May I ask why are the changelog files called 7, 9, 11? Are they the only releases that got deployed with a changelog?
If so, how would one know what to name the file when deploying a release other than by logging into the Play Dev Console to check?

**Comment by BenjaminAmos** [comment]
The changelog files are named after the Android version code for that particular release, which you can find in the project's `AndroidManifest.xml`. Fastlane only discovered the changlog for version 9 and I found the one for version 7 manually. I couldn't find any older changelogs for play store releases. The 11 one is my guess for what the `2.0.0` changelog might have been if it was released.
https://github.com/MovingBlocks/DestSolAndroid/blob/12568090752e4c423195f18df9e07c8230afc125/AndroidManifest.xml#L2-L5

**Comment by NicholasBatesNZ** [comment]
Ah right, I forgot about that. Cheers :+1:

**Comment by BenjaminAmos** [comment]
I've been testing this some more and it seems that the generated app bundles aren't including the native libraries anymore. I'll need to look into this, since the game just crashes without natives. I updated the native library logic to the one in the latest libGDX template in this pull request, so that might have something to do with it.

**Comment by BenjaminAmos** [comment]
The commit https://github.com/MovingBlocks/DestSolAndroid/pull/25/commits/eabe7f89506f549b224f154c1e5ccbe91a43dd07 should have fixed the natives issue. I couldn't reproduce it in a local development environment but when building in the Jenkins environment the issue occurred consistently (now fixed). It might possibly have been related to a race condition in gradle but I'm not sure.

**Pull request merged**
